version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET=${SECRET}
      - S3_BUCKET=${S3_BUCKET}
      - REGION=${REGION}
      - LAMBDA_FUNCTION_URL=${LAMBDA_FUNCTION_URL}